name: Create and Push Tag

on:
  workflow_dispatch:
    inputs:
      qa_cycle:
        description: 'QA n차 (예: 1, 2, 3, …)'
        required: true
        default: '1'
  workflow_call:
    inputs:
      qa_cycle:
        description: 'QA n차 (예: 1, 2, 3, …)'
        required: true
        type: string

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create and Push Tag
        env:
          QA_CYCLE: ${{ github.event.inputs.qa_cycle }}
        run: |
          # GITHUB_REF 예: refs/heads/release/1.2.3 또는 refs/heads/hotfix/1.2.3
          BRANCH=${GITHUB_REF#refs/heads/}
          # 슬래시(/)를 기준으로 분리하여 두 번째 필드가 버전 번호입니다.
          VERSION=$(echo "$BRANCH" | cut -d'/' -f2)
          TAG="${VERSION}.${QA_CYCLE}"
          echo "Creating tag: ${TAG}"
          git tag "${TAG}" "$(git rev-parse HEAD)"
          git push origin "${TAG}"
