# This is a basic workflow to help you get started with Actions

name: CI

run-name: create release ${{ github.ref_name }}-${{ github.run_number }}
permissions:
    id-token: write
    contents: write
    actions: read
    checks: write
on:
  workflow_dispatch:
    inputs:
      version_code:
        description: '버전명'
        required: true
        default: '4.18.0'

      branch_name:
        description: "release / hotfix"
        type: choice
        options:
            - release
            - hotfix

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout origin repository
                uses: actions/checkout@v3
                with:
                    ref: develop

            -   name: Configure Git
                run: |
                    git fetch --prune --unshallow --tags
                    git config user.email "hyemdooly@gmail.com"
                    git config user.name "hyemdooly"

            -   name: Create release branch
                env:
                    VERSION: ${{ github.event.inputs.version_code }}
                    BRANCH: ${{ github.event.inputs.branch_name }}
                run: |
                    git checkout -b ${BRANCH}/${VERSION}
                    git push origin ${BRANCH}/${VERSION}

            -   name: Get Head commit hash of develop branch
                id: get_head_commit_of_develop
                run: |
                  echo "head_commit_develop=$(git rev-list --max-parents=0 origin/develop)" >> $GITHUB_ENV
                  
            -   name: Get Head commit hash of develop branch
                id: get_head_commit_of_release
                run: |
                  echo "head_commit_release=$(git rev-list --max-parents=0 HEAD)" >> $GITHUB_ENV

            -   name: Make update-version.sh executable
                run: |
                    chmod +x ./update-version.sh

            -   name: update version
                id: update-version
                run: |
                    if [ ${{ env.head_commit_develop }} == ${{ env.head_commit_release }} ]; then
                        # update version
                        ./update-version.sh
                    else
                        echo "No version update required"
                    fi

                env:
                    ANDROID_HOME: ${{ vars.ANDROID_HOME }}
