# This is a basic workflow to help you get started with Actions

name: CI

run-name: update version ${{ github.ref_name }}-${{ github.run_number }}
permissions:
    id-token: write
    contents: write
    actions: read
    checks: write
on:
  push:
      branches:
          - release/**

jobs:
    build:
        if: github.event_name == 'create'
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout origin repository
                uses: actions/checkout@v3

            -   name: Configure Git
                run: |
                    git fetch --prune --unshallow --tags
                    git config user.email "hyemdooly@gmail.com"
                    git config user.name "hyemdooly"

            -   name: update version
                id: update-version
                run: |
                    # update version
                    # versionCode, versionName 변경
                    export APP_VERSION_NAME=`git branch --show-current | grep -Eo '\b[0-9]+\.[0-9]+\.[0-9]+\b'`
                    
                    # version 추출
                    IFS='.'
                    read -r MAJOR MINOR PATCH <<< "$APP_VERSION_NAME"
                    APP_VERSION_CODE=$((MAJOR * 10000 + MINOR * 100 + PATCH))
                    IFS=''
                    
                    echo "APP_VERSION_CODE=$APP_VERSION_CODE"
                    echo "APP_VERSION_NAME=$APP_VERSION_NAME"
                    
                    cat << EOF > appVersion.properties
                    appVersionCode=$APP_VERSION_CODE
                    appVersionName=$APP_VERSION_NAME
                    EOF
                    
                    # 커밋 & 푸시
                    git add .
                    git commit -m "Update Version to $APP_VERSION_NAME"
                    git push origin


                env:
                    ANDROID_HOME: ${{ vars.ANDROID_HOME }}
