# This is a basic workflow to help you get started with Actions

name: CI

run-name: create branch ${{ github.event.inputs.branch_name }}-${{ github.event.inputs.version_code }}-${{ github.run_number }}
permissions:
    id-token: write
    contents: write
    actions: read
    checks: write
on:
  workflow_dispatch:
    inputs:
        branch_name:
            description: "release / hotfix"
            type: choice
            options:
                - release
                - hotfix
        version_code:
            description: '버전명'
            required: true
            default: '0.0.0'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout origin repository
                uses: actions/checkout@v3
                with:
                    ref: develop

            -   name: Configure Git
                run: |
                    git fetch --prune --unshallow --tags
                    git config user.email github-actions
                    git config user.name github-actions@github.com

            -   name: Create release branch
                env:
                    VERSION: ${{ github.event.inputs.version_code }}
                    BRANCH: ${{ github.event.inputs.branch_name }}
                run: |
                    git checkout -b ${BRANCH}/${VERSION}
                    git push origin ${BRANCH}/${VERSION}

            -   name: Make update-version.sh executable
                run: |
                    chmod +x ./update-version.sh

            -   name: update version
                id: update-version
                run: |
                    # update version
                    ./update-version.sh

                env:
                    ANDROID_HOME: ${{ vars.ANDROID_HOME }}
