name: Create Branch(release/hotfix)
run-name: create branch ${{ github.event.inputs.branch_name }}-${{ github.event.inputs.version_code }}-${{ github.run_number }}
permissions:
    id-token: write
    contents: write
    actions: read
    checks: write

on:
    workflow_dispatch:
        inputs:
            branch_name:
                description: "release / hotfix"
                type: choice
                options:
                    - release
                    - hotfix
            version_code:
                description: '버전명'
                required: true
                default: '0.0.0'
            qa_cycle:
                description: 'QA 차수'
                required: true
                default: '1'
            commit_pointer:
                description: '시작할 커밋 SHA (지정하지 않으면 HEAD 기준)'
                required: false
                default: 'HEAD'
    workflow_call:
        inputs:
            branch_name:
                type: string # release or hotfix
                required: true
            version_code:
                type: string
                required: true
            qa_cycle:
                type: string
                required: true
                default: '1'
            commit_pointer:
                type: string
                required: false
                default: 'HEAD'
                
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout origin repository
                uses: actions/checkout@v3
                with:
                    persist-credentials: true

            -   name: Configure Git
                run: |
                    git config user.email "github-actions@github.com"
                    git config user.name "Github actions"

            -   name: Create release/hotfix branch
                env:
                    VERSION: ${{ github.event.inputs.version_code }}
                    BRANCH: ${{ github.event.inputs.branch_name }}
                    COMMIT: ${{ github.event.inputs.commit_pointer }}
                run: |
                    git checkout -b ${BRANCH}/${VERSION} ${COMMIT}
                    git push origin ${BRANCH}/${VERSION}
                    git push --set-upstream origin ${BRANCH}/${VERSION}

            -   name: Make update-version.sh executable
                run: |
                    chmod +x ./update-version.sh

            -   name: update version
                id: update-version
                run: |
                    echo "=== $REPO $NAME"
                    # update version
                    ./update-version.sh
                env:
                    ANDROID_HOME: ${{ vars.ANDROID_HOME }}
                    REPO: ${{ github.repository }}
                    NAME: ${{ github.ref_name }}
