name: PR Trigger - Do Nothing

on:
  pull_request:
    branches:
      - 'develop'
      - 'release/*'
      - 'master'

jobs:
  do-nothing:
    runs-on: ubuntu-latest
    steps:
      - name: Do Nothing
        run: echo "PR triggered, but this job does nothing."
